{
 "title": "Vault Operational",
 "description": "The most critical metrics that could indicate an immediate threat to Vault stability are included here. Alerts should be created for these.",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(vault_core_unsealed, cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Days until license expires",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((vault_core_license_expiration_time_epoch{cluster=~\"$cluster\"} - time()) / 86400)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Seal status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vault_core_unsealed{cluster=~\"$cluster\",cluster!=\"\"}",
     "legendFormat": "Cluster = {{cluster}}"
    }
   ]
  },
  {
   "title": "Autopilot node status",
   "type": "bargauge",
   "description": "Displays whether Autopilot deems the node indicated as healthy. Unhealthy status indicates a possible communication issue or other underlying problem with the target node.",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vault_autopilot_node_healthy{cluster=~\"$cluster\"}",
     "legendFormat": "Node Id = {{node_id}}"
    }
   ]
  },
  {
   "title": "Autosnapshot save errors",
   "type": "gauge",
   "description": "The number of errors encountered while trying to save autosnapshots",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vault_autosnapshots_save_errors{cluster=~\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vault Memory Utilisation",
   "type": "timeseries",
   "description": "Memory available to the Vault process.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "vault_runtime_alloc_bytes{cluster=~\"$cluster\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "vault_runtime_sys_bytes{cluster=~\"$cluster\"}",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "A good system load indicator. We recommend monitoring goroutines to establish an accurate baseline and thresholds for alerting.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vault_runtime_num_goroutines{cluster=~\"$cluster\"}",
     "legendFormat": "Goroutines"
    }
   ]
  },
  {
   "title": "Garbage collector pause rate",
   "type": "timeseries",
   "description": "GC pauses stop all vault activity. A high rate of pauses affects Vault performance. This shows a rate of GC pauses over a 5 minute period. Use a threshold of 10s for alerts.",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(rate(vault_runtime_total_gc_pause_ns[5m]) * 300) / 1e9",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Write-Ahead-Logs > Persist",
   "type": "timeseries",
   "description": "Amount of time taken to persist a Vault write-ahead logs (WAL) from the persist queue to the storage backend. An initial threshold of 1000ms is recommended. Excessive latency could indicate storage issues.",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 15 },
   "targets": [
    {
     "expr": "vault_wal_persistWALs{cluster=~\"$cluster\",quantile=\"0.99\"}",
     "legendFormat": "WAL Persist - P99"
    }
   ]
  },
  {
   "title": "Write-Ahead-Logs > Ready to Flush",
   "type": "timeseries",
   "description": "Amount of time taken to flush a Vault write-ahead logs (WAL) to the persist queue. An initial threshold of 500ms is recommended. Excessive latency could indicate storage issues.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vault_wal_flushReady{cluster=~\"$cluster\",quantile=\"0.99\"}",
     "legendFormat": "WAL FlushReady - P99"
    }
   ]
  },
  {
   "title": "Raft Commit Time",
   "type": "timeseries",
   "description": "This is the time required to commit a new entry to the raft log. Exceptions could indicate a performance issue on the leader node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vault_raft_commitTime{cluster=~\"$cluster\",quantile=\"0.99\"}",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Audit log failures",
   "type": "timeseries",
   "description": "An increase in this counter indicates that all the configured audit devices failed to log a request/response. If Vault cannot properly audit a request/response, the original request will fail.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "rate(vault_audit_log_request_failure{cluster=~\"$cluster\"}[5m])",
     "legendFormat": "Request failures"
    },
    {
     "expr": "rate(vault_audit_log_response_failure{cluster=~\"$cluster\"}[5m])",
     "legendFormat": "Response failures"
    }
   ]
  },
  {
   "title": "Rate of leadership changes (1h)",
   "type": "stat",
   "description": "Tracks the rate of leadership changes. A high leadership turnover might indicate cluster instability or communication issues.",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(vault_core_leadership_lost_count{cluster=~\"$cluster\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of leadership setup failures (1h)",
   "type": "stat",
   "description": "Tracks the rate of leadership setup failures. An increase in the rate might indicate issues with acquisition of the leadership election lock, or a wider outage impacting the cluster.",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(vault_core_leadership_setup_failed_count{cluster=~\"$cluster\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Raft leader last contact",
   "type": "timeseries",
   "description": "The amount of time since the raft leader last contacted follower nodes whilst performing a leader lease check.",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vault_raft_leader_lastcontact{cluster=~\"$cluster\",quantile=\"0.99\"}",
     "legendFormat": "P99"
    }
   ]
  }
 ]
}