scrape_configs:
  - job_name: vault
    metrics_path: /v1/sys/metrics
#    params:
#      format: ['prometheus']
    scheme: http
    static_configs:
    - targets: ['vault:8200']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
